### ISSUE TITLE
Misspelled oaut2_proxy_http variables

### ISSUE THREAD

**Issue by morganchristiansson** [morbidick/ansible-role-oauth2-proxy#2]
`oaut2_proxy_http` and `oaut2_proxy_http_sha256` are misspelled in latest release 0.2.1

Fixed in master.

With currently released role the following will use the latest version:
```
    oaut2_proxy_http: https://github.com/pusher/oauth2_proxy/releases/download/v3.1.0/oauth2_proxy-v3.1.0.linux-amd64.go1.11.tar.gz
    oaut2_proxy_http_sha256: adef7be37522b3a8b2a984402c565498da280c518d4d34ed3698274098d55472
    oauth2_filename: release/oauth2_proxy-linux-amd64
```

**Comment by morbidick** [comment]
i'll leave this open until i have fixed the CI and did a release

**Comment by morbidick** [comment]
just released v0.3.1

**Comment by morganchristiansson** [comment]
Brilliant! Thank you morbidick

**Comment by morganchristiansson** [comment]
Brilliant! Thank you morbidick
