### ISSUE TITLE
new git tag

### ISSUE THREAD

**Issue by tjend** [morbidick/ansible-role-oauth2-proxy#9]
Hi, any chance of a new git tag so I can update my ansible requirements file? Cheers :)

**Comment by shashankkoppar** [comment]
Also would be great if you guys include in this new tag  moving to https://github.com/oauth2-proxy/oauth2-proxy instead of pusher/oauth2_proxy since it has been moved there.

**Comment by morbidick** [comment]
I just tagged 0.4.0. Big thanks @tjend!
